n_hidden_channels: [1024]
n_linear_layers: [2]
n_graph_layers: [5]
n_linear_dropout: [0.2]
n_graph_dropout: [0.2]
lr: [1.e-3]
weight_decay: [1.0e-10]
batch_size: [256]
one_hot_channels: [8]
one_hot_mode: [ffn]