n_hidden_channels: [256, 1024]
n_linear_layers: [2]
n_graph_layers: [3]
p_graph_dropout: [0.2]
p_linear_dropout: [0.2]
lr: [1.e-3]
weight_decay: [1.0e-8]
batch_size: [256]
heads: [9]
do_n_sinkhorn_iters: [5]
norm_mode: ["sinkhorn"]