n_hidden_channels: [256]
n_linear_layers: [1]
n_graph_layers: [5]
p_linear_dropout: [0.2]
p_graph_dropout: [0.2]
lr: [1.e-2]
weight_decay: [1.0e-8]
batch_size: [256]
one_hot_channels: [8]
one_hot_mode: [ffn, conv]