# n_hidden_channels: [256]
# n_linear_layers: [2]
# n_graph_layers: [3]
# p_graph_dropout: [0.2]
# p_linear_dropout: [0.2]
# lr: [1.e-3]
# weight_decay: [1.0e-8]
# batch_size: [256]
# heads: [8]
# do_n_sinkhorn_iters: [5]
# norm_mode: ["gcn2"]

n_hidden_channels: [256]
n_linear_layers: [2]
n_graph_layers: [5]
p_linear_dropout: [0.2]
p_graph_dropout: [0.2]
lr: [1.e-3]
weight_decay: [1.0e-10]
batch_size: [256]
one_hot_mode: [none] #, ffn, conv
one_hot_attention: [uoi]
one_hot_incay: [indicator]
use_normal_attention: [True]
add_self_loops: [True]
one_hot_att_constant: [0.1]