n_hidden_channels: [512]
n_linear_layers: [4]
n_graph_layers: [3]
p_linear_dropout: [0.5]
p_graph_dropout: [0.2]
lr: [1.e-3]
weight_decay: [1.0e-5]
batch_size: [256]
one_hot_channels: [8]
one_hot_mode: [ffn]
first_n_one_hot: [8]