hidden_channels: [64, 256, 1028]
head_depth: [1,2,3,4]
base_depth: [3,5,10]
base_dropout: [0.5, 0.2]
head_dropout: [0.5, 0.2]
lr: [1.e-2, 1.e-3]
weight_decay: [0.0, 1.0e-10, 1.0e-8, 1.0e-5]
batch_size: [256, 64, 16]
heads: [4, 8]
do_n_sinkhorn_iters: [10]